### ISSUE TITLE
Comparison with AshOS

### ISSUE THREAD

**Issue by dusansimic** [CuBeRJAN/astOS#29]
Hi! I've recently come across this project and I love it. When I find some free time, I'll try to set it up and it might be a new os for my testing and messing around workstation.

Now the thing I can't really find much information about is how does astOS project compare to AshOS. I can see that you're the maintainer of astOS but also a contributor to AshOS and there is some similarity in the documentation. AshOS seems more generic since it should support other distros than Arch. What's recommended for use? Are there any plans for archiving astOS and focusing on AshOS?

**Comment by CuBeRJAN** [comment]
Hi,

AshOS is a project originally based on the codebase of astOS, but with many parts since rewritten.
Ash is more of a general immutability layer, which can be used with any Linux distribution. It's is less mature than astOS, but supports additional features, such as full disk encryption; astOS is more conservative.

Eventually, once AshOS becomes stable enough, astOS itself is going to move over to using the AshOS code under the hood, at least that's the plan. So no, I'm not currently planning to archive astOS, just move it over to the new codebase.

I hope this answers your questions!

**Comment by dusansimic** [comment]
Thanks you!

> I hope this answers your questions!

It indeed does.

> astOS itself is going to move over to using the AshOS code under the hood

Does that mean that astOS will essentially have the same code as AshOS or will astOS be basically AshOS but with some patches and changes that are targeted more towards Arch.

**Comment by CuBeRJAN** [comment]
> will astOS be basically AshOS but with some patches and changes that are targeted more towards Arch?

Yes, that's basically the idea!

**Comment by dusansimic** [comment]
Thank you for your answers!
